# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.actions_api import ActionsApi


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActionsApi()

    def tearDown(self) -> None:
        pass

    def test_execute_action(self) -> None:
        """Test case for execute_action

        Renderer-side execute alias. The canonical endpoint is `POST /v1/agent/actions/execute`; this path delegates to the same handler. 
        """
        pass

    def test_get_core_action(self) -> None:
        """Test case for get_core_action

        Fetch a single core action by id.
        """
        pass

    def test_list_available_actions(self) -> None:
        """Test case for list_available_actions

        List every action the agent platform exposes.
        """
        pass

    def test_list_core_actions(self) -> None:
        """Test case for list_core_actions

        List renderer-curated \"core actions\" (command-palette + keybindings backing).
        """
        pass

    def test_list_core_actions_by_platform(self) -> None:
        """Test case for list_core_actions_by_platform

        Core actions filtered to one platform.
        """
        pass

    def test_list_platform_actions(self) -> None:
        """Test case for list_platform_actions

        List actions tagged for a specific platform (notes, mail, ...).
        """
        pass


if __name__ == '__main__':
    unittest.main()
