# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.apps_api import AppsApi


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppsApi()

    def tearDown(self) -> None:
        pass

    def test_create_app(self) -> None:
        """Test case for create_app

        Register a prototype app (project_path is the on-disk root).
        """
        pass

    def test_delete_app(self) -> None:
        """Test case for delete_app

        Delete an app.
        """
        pass

    def test_delete_app_file(self) -> None:
        """Test case for delete_app_file

        Delete one file inside the app's project directory.
        """
        pass

    def test_get_app(self) -> None:
        """Test case for get_app

        Fetch an app.
        """
        pass

    def test_list_app_files(self) -> None:
        """Test case for list_app_files

        List files inside the app's project directory.
        """
        pass

    def test_list_apps(self) -> None:
        """Test case for list_apps

        List the caller's prototype apps.
        """
        pass

    def test_read_app_file(self) -> None:
        """Test case for read_app_file

        Read one file inside the app's project directory. Path is traversal-checked; returns 400 if it escapes project root. 
        """
        pass

    def test_update_app(self) -> None:
        """Test case for update_app

        Update an app.
        """
        pass

    def test_workspace_create_app(self) -> None:
        """Test case for workspace_create_app

        """
        pass

    def test_workspace_delete_app(self) -> None:
        """Test case for workspace_delete_app

        """
        pass

    def test_workspace_get_app(self) -> None:
        """Test case for workspace_get_app

        """
        pass

    def test_workspace_list_apps(self) -> None:
        """Test case for workspace_list_apps

        """
        pass

    def test_workspace_update_app(self) -> None:
        """Test case for workspace_update_app

        """
        pass

    def test_write_app_file(self) -> None:
        """Test case for write_app_file

        Write one file inside the app's project directory.
        """
        pass


if __name__ == '__main__':
    unittest.main()
