# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.notes_api import NotesApi


class TestNotesApi(unittest.TestCase):
    """NotesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotesApi()

    def tearDown(self) -> None:
        pass

    def test_create_block(self) -> None:
        """Test case for create_block

        Insert a block in a note.
        """
        pass

    def test_create_note(self) -> None:
        """Test case for create_note

        Create a note.
        """
        pass

    def test_create_note_comment(self) -> None:
        """Test case for create_note_comment

        Create a comment or reply.
        """
        pass

    def test_delete_block(self) -> None:
        """Test case for delete_block

        Delete a block.
        """
        pass

    def test_delete_note(self) -> None:
        """Test case for delete_note

        Delete a note.
        """
        pass

    def test_delete_note_comment(self) -> None:
        """Test case for delete_note_comment

        Soft-delete (native) or hard-delete (provider) a comment.
        """
        pass

    def test_disable_note_share(self) -> None:
        """Test case for disable_note_share

        Disable public sharing.
        """
        pass

    def test_enable_note_share(self) -> None:
        """Test case for enable_note_share

        Enable (or update password on) public sharing.
        """
        pass

    def test_get_block(self) -> None:
        """Test case for get_block

        Fetch one block.
        """
        pass

    def test_get_note(self) -> None:
        """Test case for get_note

        Fetch one note.
        """
        pass

    def test_get_note_comment(self) -> None:
        """Test case for get_note_comment

        Fetch one comment.
        """
        pass

    def test_get_note_share_settings(self) -> None:
        """Test case for get_note_share_settings

        Fetch share settings for a note.
        """
        pass

    def test_get_public_note(self) -> None:
        """Test case for get_public_note

        Fetch a publicly shared note.
        """
        pass

    def test_list_blocks(self) -> None:
        """Test case for list_blocks

        List blocks under a note.
        """
        pass

    def test_list_note_comments(self) -> None:
        """Test case for list_note_comments

        List comments on a note.
        """
        pass

    def test_list_notes(self) -> None:
        """Test case for list_notes

        List notes across connected accounts.
        """
        pass

    def test_move_block(self) -> None:
        """Test case for move_block

        Reparent or reorder a block.
        """
        pass

    def test_rotate_note_share_token(self) -> None:
        """Test case for rotate_note_share_token

        Rotate the share token, invalidating any outstanding URLs.
        """
        pass

    def test_update_block(self) -> None:
        """Test case for update_block

        Update a block (partial).
        """
        pass

    def test_update_note(self) -> None:
        """Test case for update_note

        Update a note (partial).
        """
        pass

    def test_update_note_comment(self) -> None:
        """Test case for update_note_comment

        Edit a comment.
        """
        pass

    def test_workspace_create_note(self) -> None:
        """Test case for workspace_create_note

        """
        pass

    def test_workspace_create_note_block(self) -> None:
        """Test case for workspace_create_note_block

        """
        pass

    def test_workspace_delete_note(self) -> None:
        """Test case for workspace_delete_note

        """
        pass

    def test_workspace_delete_note_block(self) -> None:
        """Test case for workspace_delete_note_block

        """
        pass

    def test_workspace_get_note(self) -> None:
        """Test case for workspace_get_note

        """
        pass

    def test_workspace_get_note_block(self) -> None:
        """Test case for workspace_get_note_block

        """
        pass

    def test_workspace_list_note_blocks(self) -> None:
        """Test case for workspace_list_note_blocks

        """
        pass

    def test_workspace_list_notes(self) -> None:
        """Test case for workspace_list_notes

        """
        pass

    def test_workspace_move_note_block(self) -> None:
        """Test case for workspace_move_note_block

        """
        pass

    def test_workspace_update_note(self) -> None:
        """Test case for workspace_update_note

        """
        pass

    def test_workspace_update_note_block(self) -> None:
        """Test case for workspace_update_note_block

        """
        pass


if __name__ == '__main__':
    unittest.main()
