# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.models.account_tier_details import AccountTierDetails

class TestAccountTierDetails(unittest.TestCase):
    """AccountTierDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountTierDetails:
        """Test AccountTierDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountTierDetails`
        """
        model = AccountTierDetails()
        if include_optional:
            return AccountTierDetails(
                tier = '',
                daily_api_calls = 56,
                max_connected_accounts = 56,
                max_email_sends_per_day = 56,
                max_notes = 56,
                max_sheets = 56,
                max_slides = 56,
                max_files = 56,
                max_tasks = 56,
                max_team_members = 56,
                max_workspaces = 56,
                storage_gb = 56,
                has_automations = True,
                has_advanced_automations = True,
                has_full_api_access = True
            )
        else:
            return AccountTierDetails(
                tier = '',
        )
        """

    def testAccountTierDetails(self):
        """Test AccountTierDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
