# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.conversations_api import ConversationsApi


class TestConversationsApi(unittest.TestCase):
    """ConversationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConversationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_conversation(self) -> None:
        """Test case for create_conversation

        Persist a new LLM conversation.
        """
        pass

    def test_delete_conversation(self) -> None:
        """Test case for delete_conversation

        Soft-delete a conversation.
        """
        pass

    def test_get_conversation(self) -> None:
        """Test case for get_conversation

        Fetch one conversation.
        """
        pass

    def test_get_latest_conversation_for_context(self) -> None:
        """Test case for get_latest_conversation_for_context

        Fetch the most recently active conversation for a given context tag.
        """
        pass

    def test_list_conversation_messages(self) -> None:
        """Test case for list_conversation_messages

        List messages in a conversation.
        """
        pass

    def test_list_conversations(self) -> None:
        """Test case for list_conversations

        List the caller's persisted LLM conversations.
        """
        pass

    def test_save_conversation_message(self) -> None:
        """Test case for save_conversation_message

        Append a message to a conversation.
        """
        pass

    def test_update_conversation(self) -> None:
        """Test case for update_conversation

        Update conversation metadata (title, context, cwd, session_id, pinned).
        """
        pass

    def test_update_conversation_message_metadata(self) -> None:
        """Test case for update_conversation_message_metadata

        Patch metadata on an existing message. Body must include the message id (path is the conversation id, not the message). 
        """
        pass


if __name__ == '__main__':
    unittest.main()
