# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.models.create_calendar_event201_response import CreateCalendarEvent201Response

class TestCreateCalendarEvent201Response(unittest.TestCase):
    """CreateCalendarEvent201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCalendarEvent201Response:
        """Test CreateCalendarEvent201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCalendarEvent201Response`
        """
        model = CreateCalendarEvent201Response()
        if include_optional:
            return CreateCalendarEvent201Response(
                success = True,
                data = spatio.models.spatio_event.SpatioEvent(
                    id = '', 
                    title = '', 
                    description = '', 
                    start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    all_day = True, 
                    location = '', 
                    location_details = {
                        'key' : ''
                        }, 
                    organizer = '', 
                    attendees = [
                        spatio.models.attendee.Attendee(
                            email = '', 
                            name = '', 
                            status = 'needs_action', 
                            role = 'required', 
                            optional = True, 
                            comment = '', 
                            additional_guests = 56, )
                        ], 
                    recurrence_rule = '', 
                    recurrence_id = '', 
                    original_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = '', 
                    visibility = '', 
                    busy = True, 
                    reminders = [
                        spatio.models.reminder.Reminder(
                            method = 'email', 
                            minutes = 56, )
                        ], 
                    travel_time_minutes = 56, 
                    categories = [
                        ''
                        ], 
                    color = '', 
                    user_id = '', 
                    account_id = '', 
                    provider = '', 
                    provider_id = '', 
                    provider_data = { }, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    conference_data = spatio.models.conference_data.ConferenceData(
                        type = '', 
                        uri = '', 
                        meeting_id = '', 
                        passcode = '', 
                        access_code = '', 
                        dial_in = [
                            ''
                            ], ), 
                    attachments = [
                        spatio.models.attachment.Attachment(
                            id = '', 
                            title = '', 
                            mime_type = '', 
                            url = '', 
                            size = 56, )
                        ], 
                    url = '', 
                    etag = '', 
                    sequence = 56, 
                    custom_data = {
                        'key' : ''
                        }, ),
                errors = [
                    spatio.models.calendar_account_error.CalendarAccountError(
                        account_id = '', 
                        account_name = '', 
                        error_code = '', 
                        error_message = '', )
                    ],
                metadata = { }
            )
        else:
            return CreateCalendarEvent201Response(
                success = True,
        )
        """

    def testCreateCalendarEvent201Response(self):
        """Test CreateCalendarEvent201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
