# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.platforms_api import PlatformsApi


class TestPlatformsApi(unittest.TestCase):
    """PlatformsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlatformsApi()

    def tearDown(self) -> None:
        pass

    def test_add_platform_provider_account(self) -> None:
        """Test case for add_platform_provider_account

        Add a connected account for a platform/provider pair.
        """
        pass

    def test_create_or_update_platform_secret(self) -> None:
        """Test case for create_or_update_platform_secret

        Create or update a secret value.
        """
        pass

    def test_delete_platform_secret(self) -> None:
        """Test case for delete_platform_secret

        Delete a secret.
        """
        pass

    def test_exec_platform_data(self) -> None:
        """Test case for exec_platform_data

        Run an INSERT/UPDATE/DELETE statement against a platform's store.
        """
        pass

    def test_export_platform_secrets(self) -> None:
        """Test case for export_platform_secrets

        Export all secrets for a platform (values included). Caller must be the platform owner. 
        """
        pass

    def test_generate_platform_backend_token(self) -> None:
        """Test case for generate_platform_backend_token

        Generate a short-lived backend JWT a platform's worker can use to call back into platform-service. 
        """
        pass

    def test_get_platform_catalog(self) -> None:
        """Test case for get_platform_catalog

        List the global platform catalog — every platform that exists, not just the ones the caller has installed. 
        """
        pass

    def test_get_platform_manifest(self) -> None:
        """Test case for get_platform_manifest

        Fetch a platform's manifest (capabilities, schema, UI metadata).
        """
        pass

    def test_list_platform_accounts(self) -> None:
        """Test case for list_platform_accounts

        List accounts the caller has connected for a platform.
        """
        pass

    def test_list_platform_providers(self) -> None:
        """Test case for list_platform_providers

        Discover supported providers + capabilities for a platform.
        """
        pass

    def test_list_platform_secrets(self) -> None:
        """Test case for list_platform_secrets

        List secret keys (values redacted).
        """
        pass

    def test_list_platform_tables(self) -> None:
        """Test case for list_platform_tables

        List tables in a platform's data store.
        """
        pass

    def test_list_platforms(self) -> None:
        """Test case for list_platforms

        List installed platforms for the sidebar.
        """
        pass

    def test_query_platform_data(self) -> None:
        """Test case for query_platform_data

        Run a SELECT query against a platform's data store.
        """
        pass

    def test_run_platform_migrations(self) -> None:
        """Test case for run_platform_migrations

        Run pending migrations for a platform.
        """
        pass


if __name__ == '__main__':
    unittest.main()
