# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.sheets_api import SheetsApi


class TestSheetsApi(unittest.TestCase):
    """SheetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SheetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_sheet(self) -> None:
        """Test case for create_sheet

        Create a sheet.
        """
        pass

    def test_create_sheet_row(self) -> None:
        """Test case for create_sheet_row

        Insert a row.
        """
        pass

    def test_delete_sheet(self) -> None:
        """Test case for delete_sheet

        Delete a sheet.
        """
        pass

    def test_delete_sheet_row(self) -> None:
        """Test case for delete_sheet_row

        Delete a row.
        """
        pass

    def test_get_sheet(self) -> None:
        """Test case for get_sheet

        Fetch one sheet.
        """
        pass

    def test_list_sheet_rows(self) -> None:
        """Test case for list_sheet_rows

        List rows in a sheet.
        """
        pass

    def test_list_sheets(self) -> None:
        """Test case for list_sheets

        List sheets across connected accounts.
        """
        pass

    def test_update_sheet(self) -> None:
        """Test case for update_sheet

        Update a sheet (partial).
        """
        pass

    def test_update_sheet_cell(self) -> None:
        """Test case for update_sheet_cell

        Update a single cell.
        """
        pass

    def test_update_sheet_row(self) -> None:
        """Test case for update_sheet_row

        Update a row (sparse).
        """
        pass


if __name__ == '__main__':
    unittest.main()
