# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.terminal_api import TerminalApi


class TestTerminalApi(unittest.TestCase):
    """TerminalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TerminalApi()

    def tearDown(self) -> None:
        pass

    def test_create_terminal_session(self) -> None:
        """Test case for create_terminal_session

        Create a terminal session record. PTY bytes flow renderer ↔ local-agent over IPC and never traverse this API. 
        """
        pass

    def test_delete_terminal_session(self) -> None:
        """Test case for delete_terminal_session

        Delete a terminal session record.
        """
        pass

    def test_get_terminal_session(self) -> None:
        """Test case for get_terminal_session

        Fetch a terminal session.
        """
        pass

    def test_list_terminal_sessions(self) -> None:
        """Test case for list_terminal_sessions

        List the caller's terminal sessions (metadata only — no PTY bytes).
        """
        pass

    def test_update_terminal_session(self) -> None:
        """Test case for update_terminal_session

        Update terminal session metadata (title, cwd, etc.).
        """
        pass


if __name__ == '__main__':
    unittest.main()
