# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.calendar_api import CalendarApi


class TestCalendarApi(unittest.TestCase):
    """CalendarApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarApi()

    def tearDown(self) -> None:
        pass

    def test_create_calendar_event(self) -> None:
        """Test case for create_calendar_event

        Create a calendar event.
        """
        pass

    def test_delete_calendar_event(self) -> None:
        """Test case for delete_calendar_event

        Delete an event.
        """
        pass

    def test_get_calendar_capabilities(self) -> None:
        """Test case for get_calendar_capabilities

        Per-account capability flags.
        """
        pass

    def test_get_calendar_event(self) -> None:
        """Test case for get_calendar_event

        Fetch one event.
        """
        pass

    def test_list_calendar_events(self) -> None:
        """Test case for list_calendar_events

        List calendar events across connected accounts.
        """
        pass

    def test_list_calendar_providers(self) -> None:
        """Test case for list_calendar_providers

        List supported calendar providers.
        """
        pass

    def test_sync_calendar(self) -> None:
        """Test case for sync_calendar

        Trigger a sync across connected calendar accounts.
        """
        pass

    def test_update_calendar_event(self) -> None:
        """Test case for update_calendar_event

        Update an event (sparse).
        """
        pass

    def test_workspace_create_calendar_event(self) -> None:
        """Test case for workspace_create_calendar_event

        Workspace-scoped create-event (RBAC-protected).
        """
        pass

    def test_workspace_delete_calendar_event(self) -> None:
        """Test case for workspace_delete_calendar_event

        """
        pass

    def test_workspace_get_calendar_event(self) -> None:
        """Test case for workspace_get_calendar_event

        """
        pass

    def test_workspace_list_calendar_events(self) -> None:
        """Test case for workspace_list_calendar_events

        Workspace-scoped list-events (RBAC-protected).
        """
        pass

    def test_workspace_list_calendar_providers(self) -> None:
        """Test case for workspace_list_calendar_providers

        Workspace-scoped calendar providers.
        """
        pass

    def test_workspace_update_calendar_event(self) -> None:
        """Test case for workspace_update_calendar_event

        """
        pass


if __name__ == '__main__':
    unittest.main()
