# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.models.organization_member_list_response import OrganizationMemberListResponse

class TestOrganizationMemberListResponse(unittest.TestCase):
    """OrganizationMemberListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationMemberListResponse:
        """Test OrganizationMemberListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationMemberListResponse`
        """
        model = OrganizationMemberListResponse()
        if include_optional:
            return OrganizationMemberListResponse(
                members = [
                    spatio.models.organization_member.OrganizationMember(
                        id = '', 
                        user_id = '', 
                        role = 'owner', 
                        joined_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        invited_by = null, 
                        user = { }, )
                    ],
                total = 56
            )
        else:
            return OrganizationMemberListResponse(
                members = [
                    spatio.models.organization_member.OrganizationMember(
                        id = '', 
                        user_id = '', 
                        role = 'owner', 
                        joined_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        invited_by = null, 
                        user = { }, )
                    ],
                total = 56,
        )
        """

    def testOrganizationMemberListResponse(self):
        """Test OrganizationMemberListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
