# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.folders_api import FoldersApi


class TestFoldersApi(unittest.TestCase):
    """FoldersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FoldersApi()

    def tearDown(self) -> None:
        pass

    def test_create_email_folder(self) -> None:
        """Test case for create_email_folder

        Create an email folder.
        """
        pass

    def test_delete_email_folder(self) -> None:
        """Test case for delete_email_folder

        Delete an email folder.
        """
        pass

    def test_list_email_folders(self) -> None:
        """Test case for list_email_folders

        List the caller's email folders.
        """
        pass

    def test_list_folder_emails(self) -> None:
        """Test case for list_folder_emails

        List emails inside a folder.
        """
        pass

    def test_move_emails_to_folder(self) -> None:
        """Test case for move_emails_to_folder

        Move emails into a folder.
        """
        pass

    def test_update_email_folder(self) -> None:
        """Test case for update_email_folder

        Update an email folder.
        """
        pass


if __name__ == '__main__':
    unittest.main()
