# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.models.attendee_status import AttendeeStatus

class TestAttendeeStatus(unittest.TestCase):
    """AttendeeStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttendeeStatus(self):
        """Test AttendeeStatus"""
        # inst = AttendeeStatus()

if __name__ == '__main__':
    unittest.main()
