# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_accept_workspace_invitation(self) -> None:
        """Test case for accept_workspace_invitation

        Accept a workspace invitation by token. The signed-in user's email must match the invitation. Organization-token accept lives at `POST /v1/organizations/{org}/accept-invitation`. 
        """
        pass

    def test_add_workspace_member(self) -> None:
        """Test case for add_workspace_member

        Add a member directly (skips invitation flow).
        """
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create a workspace. Requires `organizationId` in the body — bare \"personal\" workspaces aren't supported on the public API. 
        """
        pass

    def test_create_workspace_invitation(self) -> None:
        """Test case for create_workspace_invitation

        Invite a user to a workspace.
        """
        pass

    def test_get_public_invitation(self) -> None:
        """Test case for get_public_invitation

        Fetch invitation details by token (unauthenticated). Used by the renderer to show invitation context before the user signs in. 
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Fetch a single workspace by id.
        """
        pass

    def test_list_my_workspaces(self) -> None:
        """Test case for list_my_workspaces

        List the caller's workspaces (across organizations).
        """
        pass

    def test_list_workspace_invitations(self) -> None:
        """Test case for list_workspace_invitations

        List pending workspace invitations.
        """
        pass

    def test_list_workspace_members(self) -> None:
        """Test case for list_workspace_members

        List members of a workspace.
        """
        pass

    def test_remove_workspace_member(self) -> None:
        """Test case for remove_workspace_member

        Remove a member from the workspace.
        """
        pass

    def test_revoke_workspace_invitation(self) -> None:
        """Test case for revoke_workspace_invitation

        Revoke a pending workspace invitation.
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Update workspace metadata.
        """
        pass

    def test_update_workspace_member(self) -> None:
        """Test case for update_workspace_member

        Update a member's role.
        """
        pass


if __name__ == '__main__':
    unittest.main()
