# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.models.connected_app_item import ConnectedAppItem

class TestConnectedAppItem(unittest.TestCase):
    """ConnectedAppItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectedAppItem:
        """Test ConnectedAppItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectedAppItem`
        """
        model = ConnectedAppItem()
        if include_optional:
            return ConnectedAppItem(
                client_id = '',
                client_name = '',
                logo_uri = '',
                client_uri = '',
                policy_uri = '',
                tos_uri = '',
                scopes = [
                    ''
                    ],
                scope_labels = [
                    ''
                    ],
                granted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ConnectedAppItem(
                client_id = '',
                client_name = '',
                scopes = [
                    ''
                    ],
                scope_labels = [
                    ''
                    ],
                granted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testConnectedAppItem(self):
        """Test ConnectedAppItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
