# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.models.search_emails_response import SearchEmailsResponse

class TestSearchEmailsResponse(unittest.TestCase):
    """SearchEmailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchEmailsResponse:
        """Test SearchEmailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchEmailsResponse`
        """
        model = SearchEmailsResponse()
        if include_optional:
            return SearchEmailsResponse(
                emails = [
                    spatio.models.email.Email(
                        id = '', 
                        thread_id = '', 
                        provider = '', 
                        account_id = '', 
                        subject = '', 
                        from = '', 
                        to = [
                            ''
                            ], 
                        cc = [
                            ''
                            ], 
                        bcc = [
                            ''
                            ], 
                        body = '', 
                        html = True, 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        labels = [
                            ''
                            ], 
                        is_read = True, 
                        is_starred = True, 
                        attachments = [
                            spatio.models.attachment_meta.AttachmentMeta(
                                id = '', 
                                filename = '', 
                                content_type = '', 
                                size = 56, )
                            ], 
                        snippet = '', 
                        message_id = '', 
                        in_reply_to = '', 
                        references = [
                            ''
                            ], )
                    ],
                total = 56,
                next_page_token = '',
                provider = ''
            )
        else:
            return SearchEmailsResponse(
                total = 56,
                provider = '',
        )
        """

    def testSearchEmailsResponse(self):
        """Test SearchEmailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
