# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.models.organization_invitation_list_response import OrganizationInvitationListResponse

class TestOrganizationInvitationListResponse(unittest.TestCase):
    """OrganizationInvitationListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationInvitationListResponse:
        """Test OrganizationInvitationListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationInvitationListResponse`
        """
        model = OrganizationInvitationListResponse()
        if include_optional:
            return OrganizationInvitationListResponse(
                invitations = [
                    spatio.models.organization_invitation.OrganizationInvitation(
                        id = '', 
                        organization_id = '', 
                        email = '', 
                        role = '', 
                        token = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        accepted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        invited_by = null, 
                        status = 'pending', )
                    ]
            )
        else:
            return OrganizationInvitationListResponse(
                invitations = [
                    spatio.models.organization_invitation.OrganizationInvitation(
                        id = '', 
                        organization_id = '', 
                        email = '', 
                        role = '', 
                        token = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        accepted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        invited_by = null, 
                        status = 'pending', )
                    ],
        )
        """

    def testOrganizationInvitationListResponse(self):
        """Test OrganizationInvitationListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
