# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.api.native_dm_api import NativeDMApi


class TestNativeDMApi(unittest.TestCase):
    """NativeDMApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NativeDMApi()

    def tearDown(self) -> None:
        pass

    def test_add_native_dm_reaction(self) -> None:
        """Test case for add_native_dm_reaction

        Add a reaction to a DM message.
        """
        pass

    def test_attach_to_native_dm_message(self) -> None:
        """Test case for attach_to_native_dm_message

        Attach a file to a DM message.
        """
        pass

    def test_delete_native_dm_message(self) -> None:
        """Test case for delete_native_dm_message

        Delete a DM message.
        """
        pass

    def test_forward_native_dm_message(self) -> None:
        """Test case for forward_native_dm_message

        Forward a DM message to another conversation.
        """
        pass

    def test_list_native_dm_channels(self) -> None:
        """Test case for list_native_dm_channels

        List the caller's DM channels.
        """
        pass

    def test_list_native_dm_conversations(self) -> None:
        """Test case for list_native_dm_conversations

        List DM conversations with metadata (last message, unread count, etc.).
        """
        pass

    def test_list_native_dm_messages(self) -> None:
        """Test case for list_native_dm_messages

        List messages in a DM.
        """
        pass

    def test_list_native_dm_pinned_messages(self) -> None:
        """Test case for list_native_dm_pinned_messages

        List pinned messages in a DM.
        """
        pass

    def test_list_native_dm_thread_replies(self) -> None:
        """Test case for list_native_dm_thread_replies

        List threaded replies on a message.
        """
        pass

    def test_mark_native_dm_read(self) -> None:
        """Test case for mark_native_dm_read

        Mark a DM as read.
        """
        pass

    def test_mute_native_dm(self) -> None:
        """Test case for mute_native_dm

        Mute a DM.
        """
        pass

    def test_pin_native_dm_conversation(self) -> None:
        """Test case for pin_native_dm_conversation

        Pin a DM conversation in the sidebar.
        """
        pass

    def test_pin_native_dm_message(self) -> None:
        """Test case for pin_native_dm_message

        Pin a DM message.
        """
        pass

    def test_post_native_dm_message(self) -> None:
        """Test case for post_native_dm_message

        Post a DM message (top-level entry).
        """
        pass

    def test_post_native_dm_thread_reply(self) -> None:
        """Test case for post_native_dm_thread_reply

        Post a threaded reply.
        """
        pass

    def test_remove_native_dm_reaction(self) -> None:
        """Test case for remove_native_dm_reaction

        Remove a reaction.
        """
        pass

    def test_search_native_dm_messages(self) -> None:
        """Test case for search_native_dm_messages

        Search DM messages.
        """
        pass

    def test_set_native_dm_draft(self) -> None:
        """Test case for set_native_dm_draft

        Save a draft on a DM conversation.
        """
        pass

    def test_unpin_native_dm_conversation(self) -> None:
        """Test case for unpin_native_dm_conversation

        Unpin a DM conversation.
        """
        pass

    def test_unpin_native_dm_message(self) -> None:
        """Test case for unpin_native_dm_message

        Unpin a DM message.
        """
        pass

    def test_update_native_dm_message(self) -> None:
        """Test case for update_native_dm_message

        Update a DM message body.
        """
        pass


if __name__ == '__main__':
    unittest.main()
