# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spatio.models.send_email_request import SendEmailRequest

class TestSendEmailRequest(unittest.TestCase):
    """SendEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEmailRequest:
        """Test SendEmailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEmailRequest`
        """
        model = SendEmailRequest()
        if include_optional:
            return SendEmailRequest(
                account_id = '',
                to = [
                    ''
                    ],
                cc = [
                    ''
                    ],
                bcc = [
                    ''
                    ],
                subject = '',
                body = '',
                html = True,
                attachments = [
                    spatio.models.attachment_input.AttachmentInput(
                        filename = '', 
                        content_type = '', 
                        data = 'YQ==', 
                        size = 56, )
                    ],
                in_reply_to = '',
                references = [
                    ''
                    ]
            )
        else:
            return SendEmailRequest(
                to = [
                    ''
                    ],
                subject = '',
                body = '',
        )
        """

    def testSendEmailRequest(self):
        """Test SendEmailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
