# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spatio.models.rich_text_object import RichTextObject
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BlockContent(BaseModel):
    """
    Type-specific payload for a block. Fields populated depend on `Block.type`. All fields are optional at the schema level; the runtime enforces the per-type contract.  Note: this object uses snake_case keys to match the JSON the Go `providers.BlockContent` struct emits and accepts. Other parts of the SpatioAPI use camelCase; blocks are the exception because the block model is shared with external Notion-like providers whose canonical wire format is snake_case. 
    """ # noqa: E501
    rich_text: Optional[List[RichTextObject]] = None
    language: Optional[StrictStr] = Field(default=None, description="Programming language for `code` blocks.")
    checked: Optional[StrictBool] = Field(default=None, description="Toggle state for `to_do` blocks.")
    icon: Optional[StrictStr] = Field(default=None, description="Emoji or short string for `callout` blocks.")
    color: Optional[StrictStr] = Field(default=None, description="Theme color for `callout` blocks.")
    url: Optional[StrictStr] = Field(default=None, description="Source URL for `image`, `video`, `file` blocks.")
    caption: Optional[StrictStr] = Field(default=None, description="Visible caption for media blocks.")
    alt_text: Optional[StrictStr] = Field(default=None, description="Screen-reader description for media blocks. Distinct from `caption` (visible to readers) — required for accessible notes when the image conveys meaning. ")
    embed_url: Optional[StrictStr] = Field(default=None, description="Source URL for `embed` blocks.")
    cells: Optional[List[List[RichTextObject]]] = Field(default=None, description="2D rich-text grid for `table` and `table_row` blocks.")
    expression: Optional[StrictStr] = Field(default=None, description="TeX/MathJax expression for `equation` blocks.")
    __properties: ClassVar[List[str]] = ["rich_text", "language", "checked", "icon", "color", "url", "caption", "alt_text", "embed_url", "cells", "expression"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BlockContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rich_text (list)
        _items = []
        if self.rich_text:
            for _item_rich_text in self.rich_text:
                if _item_rich_text:
                    _items.append(_item_rich_text.to_dict())
            _dict['rich_text'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cells (list of list)
        _items = []
        if self.cells:
            for _item_cells in self.cells:
                if _item_cells:
                    _items.append(
                         [_inner_item.to_dict() for _inner_item in _item_cells if _inner_item is not None]
                    )
            _dict['cells'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BlockContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rich_text": [RichTextObject.from_dict(_item) for _item in obj["rich_text"]] if obj.get("rich_text") is not None else None,
            "language": obj.get("language"),
            "checked": obj.get("checked"),
            "icon": obj.get("icon"),
            "color": obj.get("color"),
            "url": obj.get("url"),
            "caption": obj.get("caption"),
            "alt_text": obj.get("alt_text"),
            "embed_url": obj.get("embed_url"),
            "cells": [
                    [RichTextObject.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["cells"]
                ] if obj.get("cells") is not None else None,
            "expression": obj.get("expression")
        })
        return _obj


