# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from spatio.models.export_pdf_request_rasterized_slides_inner import ExportPDFRequestRasterizedSlidesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExportPDFRequest(BaseModel):
    """
    Optional body for `POST /v1/slides/{id}/export/pdf`. Renderer posts pre-rasterized PNGs for slides that contain Fabric.js elements (the sidecar can't run Fabric server-side); slides without an entry are rendered from their `layout` + theme. 
    """ # noqa: E501
    rasterized_slides: Optional[List[ExportPDFRequestRasterizedSlidesInner]] = Field(default=None, alias="rasterizedSlides")
    theme: Optional[Dict[str, Any]] = Field(default=None, description="Optional palette override. Schemaless — the export sidecar accepts a free-form palette object. Treat as opaque. ")
    __properties: ClassVar[List[str]] = ["rasterizedSlides", "theme"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExportPDFRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rasterized_slides (list)
        _items = []
        if self.rasterized_slides:
            for _item_rasterized_slides in self.rasterized_slides:
                if _item_rasterized_slides:
                    _items.append(_item_rasterized_slides.to_dict())
            _dict['rasterizedSlides'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExportPDFRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rasterizedSlides": [ExportPDFRequestRasterizedSlidesInner.from_dict(_item) for _item in obj["rasterizedSlides"]] if obj.get("rasterizedSlides") is not None else None,
            "theme": obj.get("theme")
        })
        return _obj


