# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spatio.models.federated_search200_response_items_inner import FederatedSearch200ResponseItemsInner
from spatio.models.federated_search200_response_per_platform_value import FederatedSearch200ResponsePerPlatformValue
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FederatedSearch200Response(BaseModel):
    """
    FederatedSearch200Response
    """ # noqa: E501
    items: List[FederatedSearch200ResponseItemsInner]
    next_page_tokens: Optional[Dict[str, StrictStr]] = None
    per_platform: Dict[str, FederatedSearch200ResponsePerPlatformValue]
    errors: Optional[Dict[str, StrictStr]] = Field(default=None, description="Per-platform errors. Other platforms still return results.")
    total_returned: StrictInt
    took: StrictStr = Field(description="Aggregate wall-clock time for the fan-out, e.g. \"120ms\".")
    __properties: ClassVar[List[str]] = ["items", "next_page_tokens", "per_platform", "errors", "total_returned", "took"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FederatedSearch200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in per_platform (dict)
        _field_dict = {}
        if self.per_platform:
            for _key_per_platform in self.per_platform:
                if self.per_platform[_key_per_platform]:
                    _field_dict[_key_per_platform] = self.per_platform[_key_per_platform].to_dict()
            _dict['per_platform'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FederatedSearch200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "items": [FederatedSearch200ResponseItemsInner.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "next_page_tokens": obj.get("next_page_tokens"),
            "per_platform": dict(
                (_k, FederatedSearch200ResponsePerPlatformValue.from_dict(_v))
                for _k, _v in obj["per_platform"].items()
            )
            if obj.get("per_platform") is not None
            else None,
            "errors": obj.get("errors"),
            "total_returned": obj.get("total_returned"),
            "took": obj.get("took")
        })
        return _obj


