# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from spatio.models.attachment import Attachment
from spatio.models.attendee import Attendee
from spatio.models.conference_data import ConferenceData
from spatio.models.reminder import Reminder
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SpatioEvent(BaseModel):
    """
    A calendar event. Calendar uses snake_case JSON keys (different from Notes/Sheets/Slides/Tasks/Mail which use camelCase) — the surface predates the cross-platform convention. 
    """ # noqa: E501
    id: StrictStr
    title: StrictStr
    description: Optional[StrictStr] = None
    start_time: datetime
    end_time: datetime
    all_day: StrictBool
    location: Optional[StrictStr] = None
    location_details: Optional[Dict[str, StrictStr]] = Field(default=None, description="Free-form key/value (lat, lng, room, etc.).")
    organizer: Optional[StrictStr] = Field(default=None, description="Organizer email.")
    attendees: Optional[List[Attendee]] = None
    recurrence_rule: Optional[StrictStr] = Field(default=None, description="RFC 5545 RRULE.")
    recurrence_id: Optional[StrictStr] = Field(default=None, description="Set on instances of a recurring series.")
    original_start: Optional[datetime] = Field(default=None, description="Original start of a moved recurring instance.")
    status: StrictStr = Field(description="Provider-mapped event status. Free-form string — common values are `confirmed`, `tentative`, `cancelled`, `needs_action`, and the empty string when the provider doesn't populate it. Not enumerated strictly because providers add custom values and the platform passes them through verbatim. ")
    visibility: StrictStr = Field(description="Free-form visibility string. Common values: `public`, `private`, `confidential`, plus empty when unset. ")
    busy: StrictBool = Field(description="Whether this event marks the time as busy or free.")
    reminders: Optional[List[Reminder]] = None
    travel_time_minutes: Optional[StrictInt] = Field(default=None, description="Apple Calendar's local-only travel buffer. Stored on the cached row but not synced to providers that don't model it. ")
    categories: Optional[List[StrictStr]] = None
    color: Optional[StrictStr] = None
    user_id: Optional[StrictStr] = None
    account_id: StrictStr
    provider: Optional[StrictStr] = Field(default=None, description="Standardized provider id (e.g. `google-calendar`, `native-calendar`). Mirrors `provider_id` — both are populated on writes; clients should prefer `provider`. ")
    provider_id: StrictStr = Field(description="Legacy alias of `provider`.")
    provider_data: Optional[Dict[str, Any]] = Field(default=None, description="Provider-specific extras.")
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime] = None
    synced_at: Optional[datetime] = None
    conference_data: Optional[ConferenceData] = None
    attachments: Optional[List[Attachment]] = None
    url: Optional[StrictStr] = None
    etag: Optional[StrictStr] = None
    sequence: Optional[StrictInt] = None
    custom_data: Optional[Dict[str, StrictStr]] = None
    __properties: ClassVar[List[str]] = ["id", "title", "description", "start_time", "end_time", "all_day", "location", "location_details", "organizer", "attendees", "recurrence_rule", "recurrence_id", "original_start", "status", "visibility", "busy", "reminders", "travel_time_minutes", "categories", "color", "user_id", "account_id", "provider", "provider_id", "provider_data", "created_at", "updated_at", "deleted_at", "synced_at", "conference_data", "attachments", "url", "etag", "sequence", "custom_data"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpatioEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attendees (list)
        _items = []
        if self.attendees:
            for _item_attendees in self.attendees:
                if _item_attendees:
                    _items.append(_item_attendees.to_dict())
            _dict['attendees'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reminders (list)
        _items = []
        if self.reminders:
            for _item_reminders in self.reminders:
                if _item_reminders:
                    _items.append(_item_reminders.to_dict())
            _dict['reminders'] = _items
        # override the default output from pydantic by calling `to_dict()` of conference_data
        if self.conference_data:
            _dict['conference_data'] = self.conference_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # set to None if travel_time_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.travel_time_minutes is None and "travel_time_minutes" in self.model_fields_set:
            _dict['travel_time_minutes'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpatioEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "all_day": obj.get("all_day"),
            "location": obj.get("location"),
            "location_details": obj.get("location_details"),
            "organizer": obj.get("organizer"),
            "attendees": [Attendee.from_dict(_item) for _item in obj["attendees"]] if obj.get("attendees") is not None else None,
            "recurrence_rule": obj.get("recurrence_rule"),
            "recurrence_id": obj.get("recurrence_id"),
            "original_start": obj.get("original_start"),
            "status": obj.get("status"),
            "visibility": obj.get("visibility"),
            "busy": obj.get("busy"),
            "reminders": [Reminder.from_dict(_item) for _item in obj["reminders"]] if obj.get("reminders") is not None else None,
            "travel_time_minutes": obj.get("travel_time_minutes"),
            "categories": obj.get("categories"),
            "color": obj.get("color"),
            "user_id": obj.get("user_id"),
            "account_id": obj.get("account_id"),
            "provider": obj.get("provider"),
            "provider_id": obj.get("provider_id"),
            "provider_data": obj.get("provider_data"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "deleted_at": obj.get("deleted_at"),
            "synced_at": obj.get("synced_at"),
            "conference_data": ConferenceData.from_dict(obj["conference_data"]) if obj.get("conference_data") is not None else None,
            "attachments": [Attachment.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "url": obj.get("url"),
            "etag": obj.get("etag"),
            "sequence": obj.get("sequence"),
            "custom_data": obj.get("custom_data")
        })
        return _obj


