# coding: utf-8

"""
    SpatioAPI

    The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

    The version of the OpenAPI document: v1
    Contact: hello@spatio.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Task(BaseModel):
    """
    A to-do / reminder / issue. Tasks belong to one connected account (`accountId` + `provider`). Native tasks store in Spatio's DB; external providers (Linear, GitHub Issues, Todoist, etc.) round-trip through Spatio. 
    """ # noqa: E501
    id: StrictStr
    provider: Optional[StrictStr] = Field(default=None, description="Registered provider id (e.g. `native-tasks`, `linear`).")
    account_id: Optional[StrictStr] = Field(default=None, alias="accountId")
    owner_user_id: Optional[StrictStr] = Field(default=None, alias="ownerUserId")
    title: StrictStr
    description: Optional[StrictStr] = None
    status: Optional[StrictStr] = Field(default=None, description="Free-form status string. Canonical values across most providers: `todo`, `in_progress`, `in_review`, `backlog`, `done`. The platform falls back to `done` when `completed` is true and `status` is empty, else `todo`. ")
    completed: StrictBool
    due_date: Optional[datetime] = Field(default=None, alias="dueDate")
    priority: StrictStr = Field(description="Priority bucket. Canonical values (mapped from a 0–4 integer): `none`, `low`, `medium`, `high`, `urgent`. ")
    labels: Optional[List[StrictStr]] = None
    tags: Optional[List[StrictStr]] = None
    assignee_id: Optional[StrictStr] = Field(default=None, alias="assigneeId")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    completed_at: Optional[datetime] = Field(default=None, alias="completedAt")
    parent_task_id: Optional[StrictStr] = Field(default=None, description="Parent task id when this is a subtask.", alias="parentTaskId")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Provider-specific extras.")
    type: Optional[StrictStr] = Field(default=None, description="Discriminator. Canonical values: `todo`, `reminder`, `issue`. Empty defaults to `todo`. ")
    source_platform: Optional[StrictStr] = Field(default=None, description="When this task was auto-generated from another artifact (e.g. a calendar event reminder), the platform id of that artifact. ", alias="sourcePlatform")
    source_id: Optional[StrictStr] = Field(default=None, description="Source artifact id paired with `sourcePlatform`.", alias="sourceId")
    __properties: ClassVar[List[str]] = ["id", "provider", "accountId", "ownerUserId", "title", "description", "status", "completed", "dueDate", "priority", "labels", "tags", "assigneeId", "createdAt", "updatedAt", "completedAt", "parentTaskId", "metadata", "type", "sourcePlatform", "sourceId"]

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['none', 'low', 'medium', 'high', 'urgent']):
            raise ValueError("must be one of enum values ('none', 'low', 'medium', 'high', 'urgent')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Task from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if due_date (nullable) is None
        # and model_fields_set contains the field
        if self.due_date is None and "due_date" in self.model_fields_set:
            _dict['dueDate'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completedAt'] = None

        # set to None if parent_task_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_task_id is None and "parent_task_id" in self.model_fields_set:
            _dict['parentTaskId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Task from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "provider": obj.get("provider"),
            "accountId": obj.get("accountId"),
            "ownerUserId": obj.get("ownerUserId"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "completed": obj.get("completed"),
            "dueDate": obj.get("dueDate"),
            "priority": obj.get("priority"),
            "labels": obj.get("labels"),
            "tags": obj.get("tags"),
            "assigneeId": obj.get("assigneeId"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "completedAt": obj.get("completedAt"),
            "parentTaskId": obj.get("parentTaskId"),
            "metadata": obj.get("metadata"),
            "type": obj.get("type"),
            "sourcePlatform": obj.get("sourcePlatform"),
            "sourceId": obj.get("sourceId")
        })
        return _obj


